# @file
# .travis.yml - PKP Plugins Integration

dist: bionic
os: linux
language: php

addons:
  postgresql: "9.5"
  apt:
    update: true

sudo: required

php:
  - 8.0
env:
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  # Install plugin source
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/lucene

script:
  # Install data set
  - git clone https://github.com/pkp/datasets
  - cp datasets/${APPLICATION}/${BRANCH}/${TEST}/config.inc.php .
  - cp -rf datasets/${APPLICATION}/${BRANCH}/${TEST}/public/* public/
  - cp -rf datasets/${APPLICATION}/${BRANCH}/${TEST}/files/* files/
  - cat datasets/${APPLICATION}/${BRANCH}/${TEST}/database.sql | gzip > ${DATABASEDUMP}
  - ./lib/pkp/tools/travis/load-database.sh
  # Install plugin version (not included in dataset DB dump)
  - php lib/pkp/tools/installPluginVersion.php plugins/generic/lucene/version.xml
  # Run plugin test set
  - $(npm bin)/cypress run --config integrationFolder=plugins/generic/lucene/cypress/tests

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout
